### ISSUE TITLE
Get EHG-Oversampling to run with modern library versions

### ISSUE THREAD

**Issue by shaivimalik** [shaivimalik/medicine_preprocessing-on-entire-dataset#1]
Repository link: [EHG-Oversampling](https://github.com/GillesVandewiele/EHG-Oversampling)

This issue will track the process of updating the EHG-Oversampling code to:
1. Ensure compatibility with current library versions
2. Eliminate all errors

**Comment by shaivimalik** [comment]
Update requirements.txt to include the latest versions of the libraries.
Content of requirements.txt:
````
wfdb  
antropy
EMD-signal
git+https://github.com/manu-mannattil/nolitsa.git
tsfresh
smote-variants
PyWavelets
neurokit2
numpy
pandas
scipy
````

**Comment by shaivimalik** [comment]
Transition from `entropy` to `antropy`:

- Update line 4 of [ehgfeatures/features/_FeaturesRen.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesRen.py#L4)
```python 
from antropy.utils import _embed
```
- Update line 7 of [ehgfeatures/features/_FeaturesJager.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesJager.py#L7)
```python 
from antropy.utils import _embed
```
- Update line 7 of [ehgfeatures/features/_FeaturesJagerLibensek.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesJagerLibensek.py#L7)
```python 
from antropy.utils import _embed
```
- Update lines of [ehgfeatures/features/_BaseFeatures.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_BaseFeatures.py#L7)

line 7: 
```python 
import antropy
``` 
line 157: 
```python 
return {self.__class__.__name__: antropy.sample_entropy(signal, order=2, metric="chebyshev")}
```
#todo: Add comments regarding the removal of unnecessary imports.

**Comment by shaivimalik** [comment]
Transition from `neurokit` to `neurokit2`:

- Update line 6 of 
[ehgfeatures/features/_Decomposition.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_Decomposition.py#L6)
[ehgfeatures/features/_FeaturesAcharya.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesAcharya.py#L6)
[ehgfeatures/features/_BaseFeatures.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_BaseFeatures.py#L6)
```python
import neurokit2 as nk
```

- Update lines 101-115 of [ehgfeatures/features/_BaseFeatures.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_BaseFeatures.py#L6)
```python
hfd, *_ = nk.fractal_higuchi(signal, k_max=8, show=False)
return  {self.__class__.__name__:hfd}
```

**Comment by shaivimalik** [comment]
As a sanity check, I am trying to run the following code:
```python
from ehgfeatures.features import FeatureGroup, FeaturesAcharya, FeaturesJager
from ehgfeatures.signal_io import get_signals
DATA_PATH = 'data/term-preterm-ehg-database-1.0.1/tpehgdb'
ids, signals, gestations, remaining_durations = get_signals(DATA_PATH,n_signals=5)
signal = signals[0][0]
fe = FeatureGroup([FeaturesAcharya(), FeaturesJager()])
results = fe.extract(signal)
```

I am encountering the following error:
```python
Traceback (most recent call last):

  File /opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/Oversampling/EHG-Oversampling/working_experiment.py:4
    ids, signals, gestations, remaining_durations = get_signals(DATA_PATH,n_signals=5)

  File ~/Documents/Oversampling/EHG-Oversampling/ehgfeatures/signal_io.py:67 in get_signals
    return np.array(ids), np.array(signals), all_clin_names, all_clin_values

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (5, 3) + inhomogeneous part.
```

**Comment by shaivimalik** [comment]
To fix any `smote_variants` related errors like the one below:
```python
ImportError: cannot import name 'OversamplingClassifier' from 'smote_variants' (/opt/anaconda3/lib/python3.9/site-packages/smote_variants/__init__.py)
```

Update line 1 in the following files:
```python
from smote_variants import ADASYN
from smote_variants.classifiers import OversamplingClassifier
```
- [ehgfeatures/studies/peng.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/peng.py#L1)

- [ehgfeatures/studies/khan.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/khan.py#L1)

- [ehgfeatures/studies/ahmed.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/ahmed.py#L1)

- [ehgfeatures/studies/sadiahmed.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/sadiahmed.py#L1)

- [ehgfeatures/studies/jagerlibensek.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/jagerlibensek.py#L1)

- [ehgfeatures/studies/acharya.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/acharya.py#L1)

- [ehgfeatures/studies/hosseinzahde.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/hosseinzahde.py#L1)

**Comment by shaivimalik** [comment]
To prevent the error:
```python
TypeError: argument of type 'builtin_function_or_method' is not iterable
```
make the following update:
```python
_all_metrics = KDTree.valid_metrics()
```	    
at the specified lines:
- Line 26 of [ehgfeatures/features/_FeaturesRen.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesRen.py#L26)
- Line 17 of [ehgfeatures/features/_FeaturesAhmed.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesAhmed.py#L17)
- Line 43 of [ehgfeatures/features/_FeaturesJager.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesJager.py#L43)
- Line 32 of [ehgfeatures/features/_FeaturesJagerLibensek.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_FeaturesJagerLibensek.py#L32)

Update (15 July) : **Reverted this change**. The error is caused by using an older version of sklearn.

**Comment by shaivimalik** [comment]
> As a sanity check, I am trying to run the following code:
> 
> ```python
> from ehgfeatures.features import FeatureGroup, FeaturesAcharya, FeaturesJager
> from ehgfeatures.signal_io import get_signals
> DATA_PATH = 'data/term-preterm-ehg-database-1.0.1/tpehgdb'
> ids, signals, gestations, remaining_durations = get_signals(DATA_PATH,n_signals=5)
> signal = signals[0][0]
> fe = FeatureGroup([FeaturesAcharya(), FeaturesJager()])
> results = fe.extract(signal)
> ```
> 
> I am encountering the following error:
> 
> ```python
> Traceback (most recent call last):
> 
>   File /opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
>     exec(code, globals, locals)
> 
>   File ~/Documents/Oversampling/EHG-Oversampling/working_experiment.py:4
>     ids, signals, gestations, remaining_durations = get_signals(DATA_PATH,n_signals=5)
> 
>   File ~/Documents/Oversampling/EHG-Oversampling/ehgfeatures/signal_io.py:67 in get_signals
>     return np.array(ids), np.array(signals), all_clin_names, all_clin_values
> 
> ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (5, 3) + inhomogeneous part.
> ```

Update the following lines of [ehgfeatures/ /signal_io.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/signal_io.py) to fix error:

-  [Line 60](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/signal_io.py#L60)
```python
signals.append([np.array(signal_ch1),np.array(signal_ch2),np.array(signal_ch3)])
```

- [Line 65](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/signal_io.py#L65)

```python
return np.array(ids), signals, all_clin_names, all_clin_values
```

**Comment by shaivimalik** [comment]
- Update line of [ehgfeatures/features/_BaseFeatures.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/features/_BaseFeatures.py#L351)

```python
scales = (2**np.arange(scale_lim[0], scale_lim[1], scale_dens)).astype(np.int32)
```

**Comment by shaivimalik** [comment]
After making these changes, I ran [experiments/all_features.py](https://github.com/GillesVandewiele/EHG-Oversampling/tree/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/experiments/all_features.py). The script ran for approximately 6 hours on an M2 MacBook Air. Upon completion, it generated 298 CSV files.

**Comment by shaivimalik** [comment]
To fix:
```python
  File /opt/anaconda3/lib/python3.9/site-packages/smote_variants/classifiers/_oversamplingclassifier.py:27 in __init__
    self.oversampler_obj = instantiate_obj(oversampler)

  File /opt/anaconda3/lib/python3.9/site-packages/smote_variants/base/_base.py:168 in instantiate_obj
    module = importlib.import_module(description[0])

TypeError: 'ADASYN' object is not subscriptable
```
Update lines 29-30 of [ehgfeatures/studies/khan.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/khan.py#L29)
```python
oversampler = ('smote_variants', 'ADASYN', {'random_state':self.random_state})
classifier = ('sklearn.svm', 'SVC', {'kernel':'rbf', 'probability':True, 'random_state':self.random_state})
classifier= classifier if not self.grid else ('sklearn.model_selection', 'GridSearchCV', {'estimator':base_classifier, 'param_grid':grid_search_params, 'scoring':'accuracy'})
classifier= OversamplingClassifier(oversampler, classifier)
``` 

Update lines 77-79 of [ehgfeatures/studies/khan.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/khan.py#L77)    
```python
oversampler = ('smote_variants', 'ADASYN', {'random_state':random_seed})
n_classifier = ('sklearn.svm', 'SVC', {'kernel':'rbf', 'probability':True, 'random_state':random_seed})            
classifier= n_classifier if not grid else ('sklearn.model_selection', 'GridSearchCV', {'estimator':base_classifier, 'param_grid':grid_search_params, 'scoring':'accuracy'})
classifier= OversamplingClassifier(oversampler, classifier)
```

**Comment by ffund** [comment]
To do:

* bring the original EHG-Oversampling repo into this one as a subtree (should preserve commit history)
* make the changes to that repo in the subtree copy, reference issue #1 in the commit message
* then we will have a "working" copy of that repo inside this one

(after that, we can close this issue)

**Comment by shaivimalik** [comment]
- Remove the following statement from files:
```python
import pyswarms as ps
```
- Correct the SMOTE import statements:
```python
from smote_variants import SMOTE
from smote_variants.classifiers import OversamplingClassifier
```
- Ensure `shuffle=True` is included when calling StratifiedKFold:
```python
validator = StratifiedKFold(n_splits=10, random_state=random_seed, shuffle=True)
```

**Comment by shaivimalik** [comment]
> To fix:
> 
> ```python
>   File /opt/anaconda3/lib/python3.9/site-packages/smote_variants/classifiers/_oversamplingclassifier.py:27 in __init__
>     self.oversampler_obj = instantiate_obj(oversampler)
> 
>   File /opt/anaconda3/lib/python3.9/site-packages/smote_variants/base/_base.py:168 in instantiate_obj
>     module = importlib.import_module(description[0])
> 
> TypeError: 'ADASYN' object is not subscriptable
> ```
> 
> Update lines 29-30 of [ehgfeatures/studies/khan.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/khan.py#L29)
> 
> ```python
> oversampler = ('smote_variants', 'ADASYN', {'random_state':self.random_state})
> classifier = ('sklearn.svm', 'SVC', {'kernel':'rbf', 'probability':True, 'random_state':self.random_state})
> classifier= classifier if not self.grid else ('sklearn.model_selection', 'GridSearchCV', {'estimator':base_classifier, 'param_grid':grid_search_params, 'scoring':'accuracy'})
> classifier= OversamplingClassifier(oversampler, classifier)
> ```
> 
> Update lines 77-79 of [ehgfeatures/studies/khan.py](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies/khan.py#L77)
> 
> ```python
> oversampler = ('smote_variants', 'ADASYN', {'random_state':random_seed})
> n_classifier = ('sklearn.svm', 'SVC', {'kernel':'rbf', 'probability':True, 'random_state':random_seed})            
> classifier= n_classifier if not grid else ('sklearn.model_selection', 'GridSearchCV', {'estimator':base_classifier, 'param_grid':grid_search_params, 'scoring':'accuracy'})
> classifier= OversamplingClassifier(oversampler, classifier)
> ```

Make similar changes to all files within [ehgfeatures/studies](https://github.com/GillesVandewiele/EHG-Oversampling/blob/dcde9e5b25800ff6b251e0a6f4c3b252148aa398/ehgfeatures/studies)
